### ISSUE TITLE
BAD PICTURE! schubio/cfiles/profile_picture.jpg

### ISSUE THREAD

**Issue by netinetwalker** [denschub/schubio#7]
Please update and "try" to make a good picture

**Comment by denschub** [comment]
I fear you are right. Would you please submit a pull request?

**Comment by netinetwalker** [comment]
I think Photoshop is not a possible soltution. Hmm but I try to fix the picture.

**Comment by netinetwalker** [comment]
https://github.com/denschub/schubio/pull/8
